name: JavaScript Check on PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint on script.js
        run: npx eslint script.js
